name: Intermediate environment variables
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      ACTOR: ${{ github.actor }} # コンテキストの値を環境変数へセット
    steps:
      - run: echo "${ACTOR}"     # 環境変数経由でコンテキストのプロパティを参照
      - run: echo ${ACTOR}     # 環境変数経由でコンテキストのプロパティを参照
      - run: echo ${GITHUB_ACTOR}     # 環境変数経由でコンテキストのプロパティを参照
      - run: echo "${GITHUB_ACTOR}"     # 環境変数経由でコンテキストのプロパティを参照
